--liquibase formatted sql
--
-- Schema initial de Palettier.
--
-- Genere depuis le modele JPA, puis fige ici : a partir de cette version, c'est ce
-- fichier qui fait foi et le modele est seulement verifie contre lui au demarrage
-- (ddl-auto: validate). Une entite modifiee sans migration correspondante empeche
-- desormais le demarrage, au lieu de laisser la base deriver en silence.
--
-- La precondition epargne les bases anterieures a Liquibase : leur schema existe deja,
-- ce changement est alors marque comme applique sans etre rejoue.
--

--changeset palettier:001-schema-initial
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'PUBLIC' AND table_name = 'OIL_PAINT'

create table oil_paint (color_derived boolean not null, in_stock boolean not null, pigments_verified boolean not null, tinting_strength float(53) not null, user_added boolean not null, hex_color varchar(7) not null, tint_hex varchar(7), id bigint generated by default as identity, notes varchar(500), brand varchar(255) not null, code varchar(255) not null, name varchar(255) not null, drying_class enum ('FAST','MEDIUM','SLOW','VERY_SLOW') not null, opacity enum ('OPAQUE','SEMI_OPAQUE','SEMI_TRANSPARENT','TRANSPARENT') not null, primary key (id), constraint uk_paint_brand_name unique (brand, name));

create table oil_paint_pigment (paint_id bigint not null, pigment varchar(255) not null, primary key (paint_id, pigment));

create table palette (id bigint generated by default as identity, notes varchar(1000), name varchar(255) not null, purpose varchar(255) not null, primary key (id));

create table palette_paint (position integer not null check ((position>=0)), paint_id bigint not null, palette_id bigint not null, primary key (position, palette_id));

create table project (created_at timestamp(6) with time zone not null, id bigint generated by default as identity, palette_id bigint, subject varchar(1000), approach varchar(2000), notes varchar(2000), name varchar(255) not null, primary key (id));

create table project_layer (layer_position integer check ((layer_position>=0)), target_hex varchar(7) not null, id bigint generated by default as identity, zone_id bigint not null, role varchar(40) not null, technique varchar(60), note varchar(1000), kind enum ('ACCENT','LADDER') not null, primary key (id));

create table project_paint (paint_position integer not null check ((paint_position>=0)), paint_id bigint not null, project_id bigint not null, primary key (paint_position, project_id));

create table project_photo (photo_position integer check ((photo_position>=0)), added_at timestamp(6) with time zone not null, id bigint generated by default as identity, project_id bigint not null, caption varchar(200), data blob not null, role enum ('PIECE','PROGRESS','REFERENCE') not null, primary key (id));

create table project_zone (zone_position integer check ((zone_position>=0)), id bigint generated by default as identity, project_id bigint not null, note varchar(1000), material varchar(255), name varchar(255) not null, primary key (id));

create table recipe (id bigint generated by default as identity, notes varchar(1000), name varchar(255) not null, subject varchar(255) not null, primary key (id));

create table recipe_step (medium_ratio float(53) not null, step_position integer check ((step_position>=0)), id bigint generated by default as identity, recipe_id bigint not null, notes varchar(500), paint_mix varchar(255) not null, medium enum ('ALKYD_MEDIUM','COBALT_DRIER','LINSEED_OIL','NONE','ODORLESS_THINNER','STAND_OIL','TURPENTINE','WALNUT_OIL','WHITE_SPIRIT') not null, technique enum ('BASE_LAYER','BLENDING','DOT_FADING','FILTER','GLAZE','HIGHLIGHT','OIL_RENDERING','OIL_WASH','PIN_WASH','STREAKING_GRIME') not null, thickness enum ('GLAZE','IMPASTO','NORMAL','THICK','THIN') not null, primary key (id));

alter table if exists oil_paint_pigment add constraint FKf3us5qfdttde0m5qvkufby6ju foreign key (paint_id) references oil_paint;
alter table if exists palette_paint add constraint FKllbvrcw61bvawo2bd10j2rh0o foreign key (paint_id) references oil_paint;
alter table if exists palette_paint add constraint FKjswi4qr1gikk1y27yem5q7cq7 foreign key (palette_id) references palette;
alter table if exists project add constraint FKabdxjp1oofq8wouht29q4hiul foreign key (palette_id) references palette;
alter table if exists project_layer add constraint FK6vjvprbe37drftgcwqxw0jms7 foreign key (zone_id) references project_zone;
alter table if exists project_paint add constraint FKdonb4tiejbnn4af0s1w9h4h43 foreign key (paint_id) references oil_paint;
alter table if exists project_paint add constraint FKsq5ub5fcrsn7xwham2tke52p8 foreign key (project_id) references project;
alter table if exists project_photo add constraint FKci1b2v8a57ri0571usbbuyfqn foreign key (project_id) references project;
alter table if exists project_zone add constraint FKnxspdemjmkv753jjg16s9u001 foreign key (project_id) references project;
alter table if exists recipe_step add constraint FKodjhx0drj0jgeb0xnvl2g6oft foreign key (recipe_id) references recipe;
