--liquibase formatted sql
--
-- Les melanges poses sur la palette.
--
-- Le reste de l'application ne stocke aucun melange : ce sont des calculs, refaits a la
-- demande a partir des tubes du moment. Celui-ci est d'une autre nature. C'est une pate
-- reellement posee sur une palette a une heure donnee, qui reste travaillable quelques
-- heures et survit parfois plusieurs jours. Un calcul ne peut pas repondre a "est-il
-- encore ouvert ?" : il faut savoir quand il a ete fait.
--
-- Les conditions de l'atelier sont figees a la preparation, pour la meme raison que sur
-- une couche posee : c'est cet atelier-la qui a commande le temps ouvert.
--

--changeset palettier:007-melanges-sur-palette runOnChange:false
--comment Melanges poses sur la palette, avec l'heure et les conditions de leur preparation.
CREATE TABLE IF NOT EXISTS palette_mix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    hex_color VARCHAR(7) NOT NULL,
    recipe VARCHAR(500),
    drying_class VARCHAR(10) NOT NULL,
    mixed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    temperature FLOAT(53) NOT NULL,
    humidity FLOAT(53) NOT NULL,
    ventilation VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
);
